### ISSUE TITLE
ISSUES ON INSTALLATION

### ISSUE THREAD

**Issue by MELAS007** [leonardosalles/ionic2-zoom-area-example#1]
typescript: ...zoom-area/node_modules/@angular/platform-browser/src/browser/transfer_state.d.ts, line: 34
            ',' expected.

      L34:  export declare function makeStateKey<T = void>(key: string): StateKey<T>;

[13:30:15]  typescript: ...zoom-area/node_modules/@angular/platform-browser/src/browser/transfer_state.d.ts, line: 34
            Type parameter declaration expected.

      L34:  export declare function makeStateKey<T = void>(key: string): StateKey<T>;

[13:30:15]  typescript: ...zoom-area/node_modules/@angular/platform-browser/src/browser/transfer_state.d.ts, line: 34
            Expression expected.

      L34:  export declare function makeStateKey<T = void>(key: string): StateKey<T>;

[13:30:15]  typescript: ...zoom-area/node_modules/@angular/platform-browser/src/browser/transfer_state.d.ts, line: 34
            ')' expected.

      L34:  export declare function makeStateKey<T = void>(key: string): StateKey<T>;

[13:30:15]  typescript: ...zoom-area/node_modules/@angular/platform-browser/src/browser/transfer_state.d.ts, line: 34
            ';' expected.

      L34:  export declare function makeStateKey<T = void>(key: string): StateKey<T>;

[13:30:15]  typescript: ...zoom-area/node_modules/@angular/platform-browser/src/browser/transfer_state.d.ts, line: 34
            Declaration or statement expected.

      L34:  export declare function makeStateKey<T = void>(key: string): StateKey<T>;

[13:30:15]  typescript: ...zoom-area/node_modules/@angular/platform-browser/src/browser/transfer_state.d.ts, line: 34
            '(' expected.

      L34:  export declare function makeStateKey<T = void>(key: string): StateKey<T>;

[13:30:15]  typescript: ...HSC/mobile5/node_modules/@angular/platform-browser/animations/src/providers.d.ts, line: 8
            Module '"D:/EDUMASR/mobile apps/CLUBS/HSC/mobile5/node_modules/@angular/animations/browser"' has no exported
            member 'ɵDomAnimationEngine'.

       L8:  export declare function instantiateSupportedAnimationDriver(): NoopAnimationDriver;
       L9:  export declare function instantiateDefaultStyleNormalizer(): WebAnimationsStyleNormalizer;

[13:30:15]  typescript: ...zoom-area/node_modules/@angular/platform-browser/src/browser/transfer_state.d.ts, line: 34
            Object is possibly 'undefined'.

      L34:  export declare function makeStateKey<T = void>(key: string): StateKey<T>;

[13:30:15]  typescript: ...zoom-area/node_modules/@angular/platform-browser/src/browser/transfer_state.d.ts, line: 34
            Cannot find name 'key'.

      L34:  export declare function makeStateKey<T = void>(key: string): StateKey<T>;

[13:30:15]  typescript: ...zoom-area/node_modules/@angular/platform-browser/src/browser/transfer_state.d.ts, line: 34
            Cannot find name 'string'.

      L34:  export declare function makeStateKey<T = void>(key: string): StateKey<T>;

[13:30:15]  typescript: ...zoom-area/node_modules/@angular/platform-browser/src/browser/transfer_state.d.ts, line: 34
            'StateKey' only refers to a type, but is being used as a value here.

      L34:  export declare function makeStateKey<T = void>(key: string): StateKey<T>;

Error: Failed to transpile program
    at BuildError.Error (native)
    at new BuildError (D:\EDUMASR\mobile apps\CLUBS\HSC\mobile5\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at D:\EDUMASR\mobile apps\CLUBS\HSC\mobile5\node_modules\@ionic\app-scripts\dist\transpile.js:137:20
    at transpileWorker (D:\EDUMASR\mobile apps\CLUBS\HSC\mobile5\node_modules\@ionic\app-scripts\dist\transpile.js:103:12)
    at Object.transpile (D:\EDUMASR\mobile apps\CLUBS\HSC\mobile5\node_modules\@ionic\app-scripts\dist\transpile.js:61:12)
    at buildProject (D:\EDUMASR\mobile apps\CLUBS\HSC\mobile5\node_modules\@ionic\app-scripts\dist\build.js:97:78)
    at D:\EDUMASR\mobile apps\CLUBS\HSC\mobile5\node_modules\@ionic\app-scripts\dist\build.js:47:16

**Comment by bhlokhandwala** [comment]
Facing the same issue

**Comment by erBhushanPawar** [comment]
in your file : node_modules/ionic2-zoom-area/node_modules/@angular/platform-browser/src/browser/transfer_state.d.ts
`export declare function makeStateKey<T>(key: string): StateKey<T>;`

update this change and it will start working

**Comment by leonardosalles** [comment]
@erBhushanPawar this is not part of my code... if you check the path you can see NODE_MODULES

**Comment by rlmax** [comment]
same issue
